name: Deployment to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # 👈 This runs on your local GitHub Actions runner

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          cd /home/mazib/project/react-with-docker-n-docker-compose
          git checkout main
          git pull 
          docker compose down
          docker compose up --build -d
          docker image prune -f -a


# name: Deployment to VPS 

# on:
#   push:
#     branches:
#       - staging

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: SSH into VPS and Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USERNAME }}
#           key: ${{ secrets.VPS_PRIVATE_KEY }}
#           script: |
#             cd /root/ai-sales-assistant-dj
#             git checkout staging
#             git pull origin staging
#             sudo docker compose down
#             sudo docker compose up --build -d