name: Deployment to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # 👈 This runs on your local GitHub Actions runner

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          cd /home/mazib/project/react-with-docker-n-docker-compose
          git checkout main
          git pull 
          docker compose down
          docker compose up --build -d
          docker image prune -f -a